---
- name: Configure kubectl package repository
  ansible.builtin.include_role:
    name: k8s_common
    tasks_from: repository
  vars:
    k8s_package_version: "{{ k8s_kubectl_version }}"

- name: Install kubectl
  ansible.builtin.include_role:
    name: k8s_common
    tasks_from: packages
  vars:
    k8s_package_version: "{{ k8s_kubectl_version }}"
    k8s_package_names:
      - kubectl
