---
- name: Install ingress-nginx
  ansible.builtin.include_role:
    name: k8s_common
    tasks_from: ingress
  vars:
    k8s_ingress_nginx_version: "{{ ingress_nginx_version }}"

- name: Install cert-manager
  ansible.builtin.include_role:
    name: k8s_common
    tasks_from: cert_manager
  vars:
    k8s_cert_manager_version: "{{ cert_manager_version }}"
