global:
  scrape_interval: 15s
  external_labels:
    cluster: "prometheus-clash"
    replica: "0"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "clash"
    metrics_path: /metrics
    scrape_interval: 1s
    static_configs:
      - targets: ["clash-exporter.infrastructure.svc.cluster.local:2112"]

rule_files:
  - "/etc/prometheus/rules/*.yml"
