apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kubernetesVersion: 1.29.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12,2001:db8:42:1::/112
  podSubnet: 10.244.0.0/16,2001:db8:42:0::/56
apiServer:
  certSANs:
    - k8s-master.corp.aetherrootr.com
