---
- ansible.builtin.import_playbook: k8s_upgrade_step.yaml
  vars:
    k8s_previous_version: v1.29.0
    k8s_target_version: v1.29.15
    k8s_pre_calico_version: v3.29.7
    k8s_pre_cert_manager_version: v1.18.6
