all:
  children:
    kubernetes:
      children:
        k8s-master:
          vars:
            ansible_ssh_user: 'aether'
          hosts:
            k8s-master.corp.aetherrootr.com
        k8s-node:
          children:
            k8s-node-1:
              vars:
                ansible_ssh_user: 'aether'
              hosts:
                k8s-node-1.corp.aetherrootr.com
            vm-server-1:
              vars:
                ansible_ssh_user: 'aether'
              hosts:
                vm-server-1.corp.aetherrootr.com
    edge-router:
      children:
        edge-router:
          vars:
            ansible_ssh_user: 'aether'
          hosts:
            edge-router.corp.aetherrootr.com
