apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: http://prometheus.infrastructure.svc.cluster.local:9090
    jsonData:
      timeInterval: 15s
      timeout: 600
