apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: http://thanos-querier.infrastructure.svc.cluster.local:9090
    jsonData:
      timeInterval: 15s
      timeout: 600

  - name: Prometheus-clash
    type: prometheus
    access: proxy
    url: http://prometheus-clash.infrastructure.svc.cluster.local:9090
    jsonData:
      timeInterval: 15s
      timeout: 600
