server:
  port: 8080
  baseURL:  "/"
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/data"
userDefaults:
  preview:
    image: true
    popup: true
    video: true
    office: true
    highQuality: true
  darkMode: true
  disableSettings: false
  singleClick: false
  permissions:
    admin: false
    modify: false
    share: false
    api: false
