global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "homeassistant"
    scrape_interval: 60s
    metrics_path: "/api/prometheus"
    authorization:
      credentials_file: "/etc/secrets/homeassistant_token"
    scheme: https
    static_configs:
      - targets: ["ha.corp.aetherrootr.com:443"]

  - job_name: "clash"
    metrics_path: /metrics
    scrape_interval: 1s
    static_configs:
      - targets: ["clash-exporter.infrastructure.svc.cluster.local:2112"]
